@HOST = http://localhost:3333
@AUTHORIZATION = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwN2Y5YjVkODkzZTRmZDYzOGIxYzM1NCIsImlhdCI6MTYxODk3NTU5NiwiZXhwIjoxNjE5NTgwMzk2fQ.J6qlWpJOfE1QaJOtntze1Rvxo9AwVsZ6XpLZ9qGTPf8

### Login
POST {{HOST}}/sessions
Content-Type: application/json

{
  "email": "admin@fastfeet.com",
  "password": "123456"
}


### Check
GET {{HOST}}/sessions
{{AUTHORIZATION}}
