@HOST = http://localhost:3335
@AUTHORIZATION = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwN2Y5Y2YxNTBiNmNmZTRkY2NlMzQzYyIsImlhdCI6MTYxOTI3ODYwNSwiZXhwIjoxNjE5ODgzNDA1fQ.s8RW68JbRo-GkbXSreSOyOUFkem6VCdJRZNXgbjJdUg


### Index
GET {{HOST}}/delivery
  ?id_in=[1,2]
  &fk_exclude=["problems"]
{{AUTHORIZATION}}

### Index
GET {{HOST}}/delivery
{{AUTHORIZATION}}