@HOST = http://localhost:3334
@AUTHORIZATION = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODQyYWY3NzJlMjU5Y2JjYzNhOWY3NyIsImlhdCI6MTYxOTI3NDQ5NSwiZXhwIjoxNjE5ODc5Mjk1fQ.a11yOOkJI-lm096TFqa4rZdunQR7oHdhIymNZGAk9LQ


### Store
POST {{HOST}}/problems
{{AUTHORIZATION}}
Content-Type: application/json

{
  "delivery_id": "60843dee7c2d42e0329cb55d",
  "description": "Vazio."
}

### Show
GET {{HOST}}/problems
  ?id_in=[1,2,3]
  &delivery_id_in=[1,2]
  &fk_exclude=["delivery"]
  &limit=1000
{{AUTHORIZATION}}

### Show
GET {{HOST}}/problems
  ?fk_exclude=["delivery"]
{{AUTHORIZATION}}